insert into sectors_classifiers (id, sector_name) values (1, 'Manufacturing');
insert into sectors_classifiers (id, sector_name) values (19, 'Construction materials');
insert into sectors_classifiers (id, sector_name) values (18, 'Electronics and Optics');
insert into sectors_classifiers (id, sector_name) values (6, 'Food and Beverage');
insert into sectors_classifiers (id, sector_name) values (342, 'Bakery &amp; confectionery products');
insert into sectors_classifiers (id, sector_name) values (43, 'Beverages');
insert into sectors_classifiers (id, sector_name) values (42, 'Fish &amp; fish products ');
insert into sectors_classifiers (id, sector_name) values (40, 'Meat &amp; meat products');
insert into sectors_classifiers (id, sector_name) values (39, 'Milk &amp; dairy products ');
insert into sectors_classifiers (id, sector_name) values (437, 'Other');
insert into sectors_classifiers (id, sector_name) values (378, 'Sweets &amp; snack food');
insert into sectors_classifiers (id, sector_name) values (13, 'Furniture');
insert into sectors_classifiers (id, sector_name) values (389, 'Bathroom/sauna ');
insert into sectors_classifiers (id, sector_name) values (385, 'Bedroom');
insert into sectors_classifiers (id, sector_name) values (390, 'Children''s room ');
insert into sectors_classifiers (id, sector_name) values (98, 'Kitchen ');
insert into sectors_classifiers (id, sector_name) values (101, 'Living room ');
insert into sectors_classifiers (id, sector_name) values (392, 'Office');
insert into sectors_classifiers (id, sector_name) values (394, 'Other (Furniture)');
insert into sectors_classifiers (id, sector_name) values (341, 'Outdoor ');
insert into sectors_classifiers (id, sector_name) values (99, 'Project furniture');
insert into sectors_classifiers (id, sector_name) values (12, 'Machinery');
insert into sectors_classifiers (id, sector_name) values (94, 'Machinery components');
insert into sectors_classifiers (id, sector_name) values (91, 'Machinery equipment/tools');
insert into sectors_classifiers (id, sector_name) values (224, 'Manufacture of machinery ');
insert into sectors_classifiers (id, sector_name) values (97, 'Maritime');
insert into sectors_classifiers (id, sector_name) values (271, 'Aluminium and steel workboats ');
insert into sectors_classifiers (id, sector_name) values (269, 'Boat/Yacht building');
insert into sectors_classifiers (id, sector_name) values (230, 'Ship repair and conversion');
insert into sectors_classifiers (id, sector_name) values (93, 'Metal structures');
insert into sectors_classifiers (id, sector_name) values (508, 'Other');
insert into sectors_classifiers (id, sector_name) values (227, 'Repair and maintenance service');
insert into sectors_classifiers (id, sector_name) values (11, 'Metalworking');
insert into sectors_classifiers (id, sector_name) values (67, 'Construction of metal structures');
insert into sectors_classifiers (id, sector_name) values (263, 'Houses and buildings');
insert into sectors_classifiers (id, sector_name) values (267, 'Metal products');
insert into sectors_classifiers (id, sector_name) values (542, 'Metal works');
insert into sectors_classifiers (id, sector_name) values (75, 'CNC-machining');
insert into sectors_classifiers (id, sector_name) values (62, 'Forgings, Fasteners ');
insert into sectors_classifiers (id, sector_name) values (69, 'Gas, Plasma, Laser cutting');
insert into sectors_classifiers (id, sector_name) values (66, 'MIG, TIG, Aluminum welding');
insert into sectors_classifiers (id, sector_name) values (9, 'Plastic and Rubber');
insert into sectors_classifiers (id, sector_name) values (54, 'Packaging');
insert into sectors_classifiers (id, sector_name) values (556, 'Plastic goods');
insert into sectors_classifiers (id, sector_name) values (559, 'Plastic processing technology');
insert into sectors_classifiers (id, sector_name) values (55, 'Blowing');
insert into sectors_classifiers (id, sector_name) values (57, 'Moulding');
insert into sectors_classifiers (id, sector_name) values (53, 'Plastics welding and processing');
insert into sectors_classifiers (id, sector_name) values (560, 'Plastic profiles');
insert into sectors_classifiers (id, sector_name) values (5, 'Printing ');
insert into sectors_classifiers (id, sector_name) values (148, 'Advertising');
insert into sectors_classifiers (id, sector_name) values (150, 'Book/Periodicals printing');
insert into sectors_classifiers (id, sector_name) values (145, 'Labelling and packaging printing');
insert into sectors_classifiers (id, sector_name) values (7, 'Textile and Clothing');
insert into sectors_classifiers (id, sector_name) values (44, 'Clothing');
insert into sectors_classifiers (id, sector_name) values (45, 'Textile');
insert into sectors_classifiers (id, sector_name) values (8, 'Wood');
insert into sectors_classifiers (id, sector_name) values (337, 'Other (Wood)');
insert into sectors_classifiers (id, sector_name) values (51, 'Wooden building materials');
insert into sectors_classifiers (id, sector_name) values (47, 'Wooden houses');
insert into sectors_classifiers (id, sector_name) values (3, 'Other');
insert into sectors_classifiers (id, sector_name) values (37, 'Creative industries');
insert into sectors_classifiers (id, sector_name) values (29, 'Energy technology');
insert into sectors_classifiers (id, sector_name) values (33, 'Environment');
insert into sectors_classifiers (id, sector_name) values (2, 'Service');
insert into sectors_classifiers (id, sector_name) values (25, 'Business services');
insert into sectors_classifiers (id, sector_name) values (35, 'Engineering');
insert into sectors_classifiers (id, sector_name) values (28, 'Information Technology and Telecommunications');
insert into sectors_classifiers (id, sector_name) values (581, 'Data processing, Web portals, E-marketing');
insert into sectors_classifiers (id, sector_name) values (576, 'Programming, Consultancy');
insert into sectors_classifiers (id, sector_name) values (121, 'Software, Hardware');
insert into sectors_classifiers (id, sector_name) values (122, 'Telecommunications');
insert into sectors_classifiers (id, sector_name) values (22, 'Tourism');
insert into sectors_classifiers (id, sector_name) values (141, 'Translation services');
insert into sectors_classifiers (id, sector_name) values (21, 'Transport and Logistics');
insert into sectors_classifiers (id, sector_name) values (111, 'Air');
insert into sectors_classifiers (id, sector_name) values (114, 'Rail');
insert into sectors_classifiers (id, sector_name) values (112, 'Road');
insert into sectors_classifiers (id, sector_name) values (113, 'Water');
